### ISSUE TITLE
can not work in  win11 

### ISSUE THREAD

**Issue by guchangx** [Danleb/FileFaker#1]
<img width="185" alt="image" src="https://github.com/Danleb/FileFaker/assets/73569810/103aaf4b-ea3a-4768-818e-0093ded69e37">

i build source code in win11.
and i can run this client. do not have any error message.
but ,look like can not work
i drop truedata.txt in my notebook.exe then did not show fakerdata.txt content.

**Comment by Danleb** [comment]
Thanks, I will take a look.

**Comment by Danleb** [comment]
@GuBuChang Please try now, it should work. I just fixed couple of minor CLI issues, such as handling quotes in path string correctly. And I tested it on Windows 11, it works for me.
Note that I upgraded project to newer versions of all tools, since they were outdated. Use Conan2 instead of Conan1.

Please let me know if it works for you now so I can close the issue.

**Comment by guchangx** [comment]
<img width="959" alt="image" src="https://github.com/Danleb/FileFaker/assets/73569810/5ac404f9-6cd8-4774-a856-8b942adf16a6">

it can work.
Thank you for your reply
Thank you for your repo
that is very cool and amazing project
i am learning
the C++ world should thank you for making a difference by this project
